[]
ecsimsw/java-hangman pull request #1
Opened 2023-05-29 18:40 UTC by hyunsb

2023-05-30 04:19 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
게임 결과를 출력하는 기능을 구현하며 두 가지 구현방식이 떠올랐습니다.
1. `Iterable`을 구현하여 해당 클래스외부에서 각 라운드에 접근하여 데이터를 출력하는 방식
2. 내부에서 Map을 순회하며 결과를 만들어 반환하는 방식

1번으로 구현하면 외부에서 컬렉션을 순회하며 데이터에 접근하다 보니 코드가 지저분해지는 느낌이고
2번으로 구현하자니 결과를 만드는 행위가 라운드의 결과를 저장하는 `HangmanGameRoundTable`과는 어울리지 않는 느낌이 들었습니다. 

두 가지 방식 모두 마음에 안드니 일단 코드가 깔끔해지는 2번으로 구현을 진행했는데
여러분이라면 어떤 방식으로 구현하셨을까요?

2023-05-30 04:22 UTC, hyunsb commented on src/test/java/src/view/InputViewTest.java
> +        Assertions.assertEquals('a', singleAlphabet);
해당 테스트 코드의 동작이 서로 독립적이지 않게 되었습니다.

구글링과 chatGPT에게 물어보며 이것저것 한 5가지 정도 해결책 찾아서 적용해봤는데도
먼저 실행되는 테스트코드의 입력 값이 다른 테스트 코드에게 영향을 미치더라구요.

해결책을 찾아봐야겠습니다.

2023-05-30 04:23 UTC, hyunsb commented on src/main/java/src/view/InputView.java
> +    }
기본적인 입력값 유효성검사는 View에서 모두 처리하려 했습니다.
그러다보니 View의 코드가 점점 길어지더라구요.

좋은 해결책이 있을까요?

2023-05-30 04:27 UTC, hyunsb commented on src/main/java/src/hangmanGame/Hangman.java
> +    public static class HangmanInfo {
InputView에서 게임 횟수와 목숨을 한 번에 받아오기 위해 독립적으로 생성될 수 있는
정적 내부 클래스를 선언해봤습니다.

적절한 사용 방식이 맞을까요?

2023-05-30 08:34 UTC, ecsimsw commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
저라면 이미 view를 따로 나눠두셨으니, gameResult와 roundTable을 view에 넘기고 view에서 처리했을 것 같습니다.
뷰와 HangmanGameRoundTable이 애매하게 나뉘어져 있어 화면의 출력이 바뀌면 HangmanGameRoundTable이 바뀌는 꼴이라는 생각이 드네요. 

예를 들면 `\n=== Game Result ===\n`가 `== game result==`로 바뀐다는 간단한 요구사항 변동이 생긴다고 가정합시다. 아마 현수님이 OutputView를 계획하셨을 때 OutputView만 코드 수정이 일어나고 HangmanGameRoundTable은 변경에 영향을 받지 않는 구조를 의도하시진 않았을까라는 생각이 드네요. 

그렇다면 만약 그렇다면 HangmanGameRoundTable에서 "\n=== Game Result ===\n"이나 "남은 목숨 : %d, %s, 사용자 입력 : %c\n"는 빠질 수 있도록 하고, 화면에 어떻게 출력되는지는 OutputView에서 신경쓰는 방법은 어떨까요?

``` java
private void viewGameResult() {
    try {
        int gameId = InputView.inputNumberOf(INPUT_GAME_ID);
        HangmanGameRoundTable roundTable = gameTable.getRoundTableWithException(gameId);
        OutputView.printGameResult(roundTable.getGameResult());
        OutputView.printRoundResult(roundTable.getRoundTable());
    } catch (IllegalArgumentException exception) {
        OutputView.printMessage(exception.getMessage());
    }
}
```

2023-05-30 08:41 UTC, ecsimsw commented on src/main/java/src/view/InputView.java
> +    }
원시값을 포장하여 객체로 값을 다루면 어떨까요?
지금 47번째 줄의 numberGames와 life는 믿을 수 있는 numberGames, life 값일까요? 각각은 음수일 수도 있고, 미션에 아직은 없는 요구사항에 위반될 수도 있을겁니다 (예를 들면, life는 반드시 홀수다! 라는 조건이 이후에 추가되었다고 생각해보세요.)

아래처럼 그냥 int 값 뿐이었던 변수들을 객체로 포장하면서, 객체의 생성 시에 유효성을 검증하면 검증 로직의 위치가 명확해지니 코드 관리에도 편하고 해당 라인 자체에서 믿을 수 있는 값을 갖도록 할 수 있을 것 같은데 이런 아이디어는 어떠신가요? ㅎㅎ
``` java
NumberGame numberGames = new NumberGame(Integer.parseInt(gameNumberAndLife[INDEX_NUMBER_GAMES]));
Life life = new Life(Integer.parseInt(gameNumberAndLife[INDEX_LIFE]));
```

2023-05-30 09:04 UTC, ecsimsw commented on src/test/java/src/view/InputViewTest.java
> +        Assertions.assertEquals('a', singleAlphabet);
이 테스트는 두가지를 동시에 하려는 것 같은 생각이 드네요!

1. 인풋 스트림이 제대로 동작하는지
2. Hangman 객체가 인자로 입력받은 문자열을 제대로 처리하려 하는지

제 생각엔 1번 테스트는 자바 유틸을 테스트 하는 것 같아 크게 의미를 안갖고 믿으셔도 될 듯 합니다. 정 테스트하고 싶으시다면 Hangman 이 아니라 다른 파일에서 1번만 테스트해도 좋겠네요

그래서 이 사용자 입력이 제대로 됨은 믿고 아래처럼 Hangman 객체가 생성되면서 제대로 구분자를 기준으로 life와 게임수를 갖는지 테스트하는 것도 테스트에 의미를 갖을 것 같다고 생각합니다!!

'''
String userInput = game + SEPARATOR + life;
Hangman hm = new HangMan(userInput);
verifyEquals(hm.life, life);
verifyEquals(hm.game, game);
'''

2023-05-30 10:09 UTC, hyunsb commented on src/main/java/src/view/InputView.java
> +    }
좋은 의견 감사합니다!
이번에 과제 진행하면서 왜 원시값 포장하는 래퍼 클래스를 만들어야 되는지 알게 되었습니다.

`numberGames`와 `life`를 각각 포장하려니 쓸데없는 클래스가 너무 생길 것 같아서
`Hangman`클래스 안에 중첩 클래스로 만들어 놓긴 했는데 해당 방법이랑은 차이가 있는걸까요??
검증은 해당 클래스에서 진행하고 있습니다.
``` java
public class Hangman {
    ...
    public static class HangmanInfo {

        public final int numberGames;
        public final int life;

        public HangmanInfo(int numberGames, int life) {
            validateNumberGames(numberGames);
            validateLife(life);
            this.numberGames = numberGames;
            this.life = life;
        }
        ...
}
```
정규식을 쓰면 코드가 더 간단해질 줄 알았는데 더 지저분해진 느낌이네요,,
사용자 입장에서는 자기가 입력한 값이 뭐였는지 헷갈리는 경우도 존재할 거 같구요
정규식을 안쓰는 방식으로 한 번 바꿔봐야 겠습니다.

2023-05-30 10:19 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
오호 그렇네요! 

현재 코드에서는 `OutputView`가 존재하는데도 그 역할을 다른 클래스가 수행하고 있는 느낌이네요.
그래서 코드가 지저분해 보인다고 생각이 들었나 봅니다.

이런 걸 어떻게 코드를 슥 보고 찾아내시는지 대단하십니다,,

결과 출력을 위한 상수들을 `OutputView`로 넘기고 
`OutputView`에서 결과를 출력하도록 해보겠습니다.

2023-05-31 07:52 UTC, ecsimsw commented on src/main/java/src/view/InputView.java
> +    }
위  while (true) 문도, 아래 try -catch 후 재귀도, 사용자 입력에 예외가 있는 상황에서 다시 받기 위한 로직인거 같네요~
그 둘을 나눈 기준은 어떻게 될까요?

``` java
public static Hangman.HangmanInfo inputHangmanInfo() {
    try {
        String[] input = inputOf(NUMBER_OF_GAME_AND_LIFE).split(","); 
        return new Hangman.HangmanInfo(input[INDEX_NUMBER_GAMES], input[INDEX_LIFE]);
    } catch(ArrayIndexOutOfBoundsException e) {
        OutputView.printMessage(ERR_INPUT_CORRECT_VALUE_NUMBER_OF_GAME_AND_LIFE);
    } catch (IllegalArgumentException exception) {
        OutputView.printMessage(exception.getMessage());
        return inputHangmanInfo();
    }
}
```

2023-05-31 07:55 UTC, ecsimsw commented on src/main/java/src/hangmanGame/Hangman.java
> +    public static class HangmanInfo {
오호 
근데 현수님은 어떤 방식이 더 좋다고 생각하세요? 
정답은 없을 것 같은데 이 내부 클래스를 사용하신 이유가 반대로 궁금하네요!!

2023-05-31 08:48 UTC, ecsimsw requested changes

2023-05-31 08:48 UTC, ecsimsw commented on src/main/java/src/hangmanGame/HangmanGame.java
> +    HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
접근 제한자를 default로 의도한 이유가 있을까요?

2023-05-31 10:45 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGame.java
> +    HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
처음엔 public이었는데 코드를 다 작성하고보니
위치한 패키지 밖에서는 사용되지 않아서 package private로 선언했습니다.

추후 테스트코드 작성한다면 다시 public으로 열어줄 생각입니다.

2023-05-31 10:54 UTC, hyunsb commented on src/main/java/src/hangmanGame/Hangman.java
> +    public static class HangmanInfo {
HangmanInfo 라는 내부 클래스가 독립적으로 어떤 행위를 수행하진 않고
Hangman에 종속되는 클래스라는 느낌이 들었습니다. 

객체지향적인 느낌이 아닌 그저 껍데기 클래스 느낌? 이라고 해야될까요

실제로 HangmanInfo 클래스의 멤버가 Hangman 객체 안에서만 사용되기 때문에
외부에서도 Hangman.HangmanInfo 로 접근하는 게 더 의미를 파악하기 좋겠다고 생각했습니다!

지금보니까 클래스 이름을 HangmanInfo 대신 Info 로 변경하여
Hangman.Info 로 접근하는 게 좋았을 것 같네요!

2023-05-31 11:29 UTC, ecsimsw commented on src/main/java/src/hangmanGame/HangmanGame.java
> +    HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
현수님 되게 신나셨군요.
되게 즐기고 계시는거 같아 참 기분이 좋아요 😀 

지금 생성자는 가급적 좁은 범위로 두고 싶어서 팩토리 메서드를 public으로 두고 생성자는 private으로 하시겠다는거죠?

근데 그럼 어떤 점이 좋은가요? 그렇게 하는 이유가 궁금합니다!

2023-05-31 11:49 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGame.java
> +    HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
이번 미션이 뭔가 저랑 잘맞는 느낌이 드네요 ㅎㅎ😁
얼른 다른 분들 코드도 구경하고 싶습니다.

public 클래스의 public 메서드는 API가 되어버리기 때문에
외부에서 봤을 때 생성자를 통해 객체를 생성하기 보다는 팩토리 메서드를 사용하는 게
메서드 이름에서 생성 의미를 유추할 수 있기때문에 더 직관적이라고 생각합니다.

그리고 개인적으로 생성자에서 어떤 검증로직이 이루어지는 것 보다는
팩토리 메서드에서 검증로직이 이루어지고, 
모든 전처리가 끝난 이후 new로 객체를 생성하는 게 더 깔끔해보입니다!

2023-05-31 12:04 UTC, hyunsb commented on src/main/java/src/view/InputView.java
> +    }
앗! 그렇네요 ㅎㅎㅎ 부끄럽군요,,
멘토님이 알려주신 방향으로 리팩터링 해보겠습니다!

2023-05-31 13:35 UTC, ecsimsw commented on src/main/java/src/hangmanGame/HangmanGame.java
> +    HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
아하!
정적팩토리 메서드를 쓰고 생성자를 private으로 못쓰게 묶고 싶다는거였군요~ 
좋네요 ㅎㅎ

2023-05-31 17:04 UTC, hyunsb commented on src/main/java/src/view/InputView.java
> +            return inputMenuNumber();
탑 레벨 클래스로 분리 시켰습니다.
Commit: https://github.com/ecsimsw/java-hangman/pull/1/commits/cfdb1a56521aa6c580a77c244c69ee3511ab221a

2023-05-31 17:26 UTC, hyunsb commented on src/main/java/src/view/InputView.java
> +            return inputMenuNumber();
해당 문제에 대해 또 한가지 고민거리가 생겼습니다.

래퍼 클래스 사용 시 너무 많은 인스턴스가 생성되는 것은 아닐까요?
메뉴 입력은 그다지 많은 인스턴스가 생성되진 않을 것 같은데

알파벳 입력에서는 너무 많은 인스턴스가 생성될 것 같습니다. (Commit: https://github.com/ecsimsw/java-hangman/pull/1/commits/17ee48dd0a1ff6c34b63d22230bbd03585dae722)

일단 메뉴 입력 부분은 미리 인스턴스를 생성해놓고 캐싱하여 사용하는 방식으로 변경해봤는데 (Commit: https://github.com/ecsimsw/java-hangman/pull/1/commits/e5dbc99465ebff88c44fcaf26a952215b5978430)
`MenuNumber` 객체를 반환하는 정적 팩토리 메서드에서 입력값 검증을 진행해야 된다는 부분이 마음에 걸리네요.

너무 어렵습니다,,,😥😥😥

2023-05-31 18:07 UTC, hyunsb commented on src/main/java/src/view/InputView.java
> +            return inputMenuNumber();
알파벳도 미리 인스턴스를 생성해놓고 Key를 통해 캐싱하여
인스턴스를 반환하는 방법으로 변경해봤습니다. (Commit: https://github.com/ecsimsw/java-hangman/pull/1/commits/ae8afd2cb4b9efd25b313aabcda7abe265aed3df)

여전히 팩토리 메서드에서 검증을 진행한다는 점이 마음에 걸리네요.

2023-06-01 00:19 UTC, ecsimsw commented on src/main/java/src/view/InputView.java
> +            return inputMenuNumber();
고민하시는 부분이 원시 타입을 포장하는 클래스가 매번 인스턴스 생성된다는 문제와 값을 반환할지 인스턴스 자체를 넘길지를 고민하시는게 맞을까요?

일단 캐싱은 좋은 아이디어 같습니다. 두번째는 접근제한자에 너무 얽매이지 않으셨으면 좋겠다는 생각이 드네요. 이전 default 를 사용하셨을 때의 피드백도 비슷한데 이 클래스가 어떤 범위로 사용될지를 고민하고 접근제한자를 설정해야지, 접근제한자를 default나 private으로 만들려면 어떻게 해야하지 -> 정적 팩토리 메서드를 만들고 그걸 public으로 열어야 겠다, 또는 클래스를 옮기거나 패키지를 바꿔야지처럼 주와 부가 바뀌게 된건 아닌지 싶네요.

클래스의 사용 범위를 고민하는 것은 참 좋은 고민이라고 생각합니다. 접근 제한자를 어떻게 할지보다 그래서 이 클래스가 어떻게 사용될지를 먼저 산정하면 어떨까요.

예를 들면 저라면 inputView에서 생성해서 넘기고, 원시 값 자체를 받아오는 것은 정말 딱 view에서 표시할 때 빼고는 가급적 포장하여 사용할 것 같습니다. 
현수님은 이 클래스가 어떻게 사용될거 같으신가요?

2023-06-01 00:41 UTC, ecsimsw commented on src/main/java/src/view/InputView.java
> +            return inputMenuNumber();
이건 이따 같이 코드 보면서 대화하면 좋겠네요 😀

2023-06-01 02:19 UTC, hyunsb commented on src/main/java/src/view/InputView.java
> +            return inputMenuNumber();
알파벳은 미리 모든 알파벳에 대해 인스턴스를 생성하기 보다는

파라미터로 넘어온 알파벳에 대한 `SingleAlphabet` 인스턴스가 캐시에 존재하지 않는다면
객체를 생성하고 캐시에 저장한 후 반환하고

알파벳에 대한 `SingleAlphabet` 인스턴스가 캐시에 존재하면 이를 반환하는 방식으로 변경해봤습니다.
Commit: https://github.com/ecsimsw/java-hangman/pull/1/commits/b04776a464c66877549536379553bc735448fbd3

2023-06-01 03:59 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGame.java
> +    HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
``` java
HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
        this.gameId = numberGames;
        this.life = life;
        this.word = word.getSpelling();
        this.roundTable = roundTable;

        correctingWord = BLANK_ALPHABET.repeat(this.word.length());
        gameResult = GAME_FAIL;
    }
```

위의 `HangmanGame`의 생성자를 package-private으로 놔둔 이유입니다.

해당 생성자는 같은 패키지 내의 `Hangman` 클래스에서만 이루어지는 것을 의도했습니다.

`HangmanGame`은 클래스 내부에서 멤버에 대한 검증과정이 이루어지지 않기 때문입니다.
따라서 `HangmanGame`이 의도한 대로 작동하려면 `Hangman` 클래스에서 멤버를 주입시켜줘야 하기 때문에
package-private으로 접근제한자를 설정했습니다.

2023-06-01 05:06 UTC, chaewon12 commented on src/main/java/src/hangmanGame/Hangman.java
> +            chooseMenu();
`chooseMenu`를 hangmanGame 설정 후 하는 이유가 있을까요?
게임 진행은 안하고 결과만 보려고 했을 떄는 어떻게 되는 건가요?

2023-06-01 05:16 UTC, chaewon12 commented on src/main/java/src/dto/MenuNumber.java
> +
메뉴 번호가 지금처럼 연속적이지 않게 변경된다면 어떤 문제점이 생기나요?

2023-06-01 05:18 UTC, chaewon12 commented on src/main/java/src/dto/MenuNumber.java
> +    }
먼저, 여기에서 수정이 생길 것 같아요

2023-06-01 05:20 UTC, chaewon12 commented on src/main/java/src/hangmanGame/Hangman.java
> +        }
메뉴 번호가 바뀌면 여기도 수정해야 겠네요

2023-06-01 05:30 UTC, hyunsb commented on src/main/java/src/hangmanGame/Hangman.java
> +            chooseMenu();
코드리뷰 감사합니다!

요구사항의 메뉴 선택에서 게임 종료 메뉴가 없어서 
모든 행맨 게임이 완료되면 자동으로 종료되게끔
의도하고 생성하였습니다!

채원님 말씀대로 게임 진행 전 결과만 보는 기능을 추가하려면
게임 종료를 포함하는 새로운 코드를 추가해야 겠네요 ㅎㅎ😊

2023-06-01 05:36 UTC, hyunsb commented on src/main/java/src/dto/MenuNumber.java
> +
음,, 앞서 남겨주신 리뷰를 감안해서 구현한다면
메뉴와 관련된 데이터를 모아서 enum 클래스를 생성하고 
이를 활용해서 구현 할 것 같아요!

2023-06-01 05:38 UTC, hyunsb commented on src/main/java/src/dto/MenuNumber.java
> +    }
그쵸 메뉴 enum 클래스를 만든다면
이부분은 메뉴 클래스의 상태에 따라
유동적으로 범위를 검증하는 형식이 되겠네요!

2023-06-01 05:38 UTC, chaewon12 commented on src/main/java/src/hangmanGame/HangmanGame.java
> +        OutputView.printMessage(String.format(GAME_EPISODE_INFO_FORMAT, gameId, word.length()));
와! 저도 이런 출력 부분 처음에는 `gameId+"번째 게임"` 이런식으로 작성했다가
String.format 을 사용하는 방법으로 리팩토링 했는데 같은 생각이셨군요 👍

2023-06-01 05:40 UTC, hyunsb commented on src/main/java/src/hangmanGame/Hangman.java
> +        }
이 부분도 위와 마찬가지겠네요!

만약에 메뉴 클래스를 구현한다면
개인적으로 좋은 방식은 아닐거라 생각되지만
리플렉션을 사용해서 메서드를 배열에 저장하고 불러오는 방식을 사용해보고 싶네요!

2023-06-01 05:44 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGame.java
> +        OutputView.printMessage(String.format(GAME_EPISODE_INFO_FORMAT, gameId, word.length()));
죠습니다!
저는 포맷을 상수로 관리할 수 있어서 이 방법이 제일 깔끔하다고 생각되었어요.

2023-06-01 05:52 UTC, chaewon12 commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
라운드id 가 맞는지 확인 하는 부분에서 map.containskey() 메서드 대신 size로 비교한 이유가 궁금합니다..!
혹시 containskey의 단점 같은게 있나요🤔

2023-06-01 06:02 UTC, chaewon12 commented on src/main/java/src/hangmanGame/RandomWordChooser.java
> +    }
`WORDS` 가 chooseWord() 내에서 말고도 쓰이는 곳이 있나요?
랜덤값을 뽑을 때 HangmanWord.values()에서 바로 접근해도 될 것 같은데 따로 list 저장 하신 이유가 궁금합니다!

아니면, chooseWord() 내에서만 쓰인다면 chooseWord() 내 지역 변수가 아닌 전역인 이유도 궁금하고요!

2023-06-01 06:04 UTC, chaewon12 commented on src/main/java/src/view/InputView.java
> +    private static final String CHOICE_GAME_MENU = "메뉴를 선택합니다. (1 : 게임하기, 2 : 게임 결과 보기, 3 : 라운드 결과 보기)";
이부분은 하드 코딩 되어있는 것 같아요!
메뉴 번호나 메뉴 이름이 변경될 수 있을 것 같아요

2023-06-01 06:05 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
`roundTable`의 구현이 `TreeMap`이기 때문에
`containsKey`메서드를 사용한다면 O(logN)의 시간이 걸립니다.
하지만 `roundTable.size()` 의 상수 비교를 통해 비교한다면 O(N) 시간이 걸립니다.
따라서 성능을 높이려고 작성했습니다만 큰 의미는 없어 보입니다 ㅎㅎ,,

처음엔 해당 `Map`의 구현 클래스를 `HashMap`으로 지정했습니다.
행맨 프로젝트에서는 `map`에 저장되는 데이터가 많지 않기 때문에
해시충돌은 일어나지 않는다고 봐도 무방하다고 생각합니다.

하지만 데이터가 엄청나게 많다고 가정했을 때 해시 충돌이 여러번 일어나게 된다면
`hashMap`의 `containskey()` 연산의 시간복잡도는 O(logN)이 될 것을 고려해서 작성했습니다.
`roundTable.size()` 의 상수 비교를 통해 성능을 높이려고 했습니다.

2023-06-01 06:05 UTC, chaewon12 commented on src/main/java/src/view/InputView.java
> +    private static final String ERR_INPUT_CORRECT_VALUE_NUMBER_OF_GAME_AND_LIFE = "게임 횟수와 목숨을 ','로 구분하여 차례대로 입력 해주세요.\n";
여기도 구분자가 / 로 변경되면 문구를 모두 고쳐야 하지 않을까요?

2023-06-01 06:08 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
채원님 덕분에 제 코드에 대한 생각을 다시 정리하는 시간이 되었네요 감사합니다!

2023-06-01 06:15 UTC, hyunsb commented on src/main/java/src/hangmanGame/RandomWordChooser.java
> +    }
음,, 그러네용 
저는 `WORDS`에서 랜덤 단어를 선택한다는 게 클래스의 역할과 맞지 않는다고 생각이 들었어요
`WORDS`에서는 단어를 저장하는 역할만 가지게 하고 싶었습니다.

이번 과제부터 멀티 스레드 환경을 슬금슬금 생각해보려고 했습니다.
따라서 단어들을 모두 불변에 싱글톤으로 관리하려고 리스트로 만들었는데

생각해보니 `WORDS`에서 생성되는 객체들은 싱글톤으로 관리되니까 리스트로 만들 필요가 없었군요!

2023-06-01 06:15 UTC, chaewon12 reviewed
안녕하세요 현수님
코드에 고민의 흔적이 많이 느껴져서 저도 같이 고민하면서 읽었던 것 같아요!

구조에 대한 리뷰는 제가 실력이 아직 부족해서 잘 못드리겠지만..
코드 보면서 궁금했던 내용이나 하드코딩된 곳은 없는지를 위주로 리뷰 남겼습니다!!

2023-06-01 06:20 UTC, chaewon12 commented on src/main/java/src/hangmanGame/Hangman.java
> +            chooseMenu();
아하 저도 게임 종료 메뉴가 없어서 고민하다가 저는 종료 메뉴를 추가했어요ㅋㅋ
그러면 행맨게임시작-> 결과보기-> 종료 이렇게 동작 하는 건가요!?

2023-06-01 06:25 UTC, chaewon12 commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
오.. 그러면 지금처럼 아이디가 +1씩 연속적으로 증가하는 경우에는 size로 비교하는 방법이  빠르겠네요!!
시간복잡도 까지 생각하시면서 작성하신다니 대단하세요...

2023-06-01 06:27 UTC, ecsimsw commented on src/main/java/src/hangmanGame/HangmanGame.java
> +    HangmanGame(int numberGames, int life, HangmanWord word, HangmanGameRoundTable roundTable) {
`해당 생성자는 같은 패키지 내의 Hangman 클래스에서만 이루어지는 것`
이라고 해주셨는데, 꼭 Hangman 클래스가 아니더라도 모든 해당 패키지에서 생성이 가능할 것 같아요. 

'HangmanGame은 클래스 내부에서 멤버에 대한 검증과정이 이루어지지 않기 때문'이 이유라고 하면 HangmanGame 내부에서 멤버 검증이 이뤄지고 차라리 생성자는 노출이 되면 어떨까요?
생성자는 애매하게 패키지 단위로 숨겨지고, 내부 값에 대한 검증은 밖에 있으니 이런 일이 생기는 것 같아요.

딱 다른 것 없이 HangmanGame은 결국 음수의 life를 갖고 있는 꼴이 나올 수 있겠네요!?
지금 HangmanGame이 생성자가 default인 이유는 현수님만 아시는 코드인 것 같아요. 
(`HangmanGame 내부에서 값 검증을 안하니 패키지로 범위를 줄이는데, 그 중에서도 Hangman 클래스에서 값을 만들어 주입해주길 바랍니다.` 라는 의도를 말이죠.)

2023-06-01 06:38 UTC, ecsimsw commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
```
if (roundId > roundTable.size()) throw new IllegalArgumentException("해당 라운드 정보는 존재하지 않습니다.");
```
이 내용은 roundId가 roundTable의 사이즈 안에서 생성된다는 내용이 베이스로 깔려야겠네요!!
그걸 이 메서드만 보고 다른 팀원들도 알 수 있을까요? 

오오 bucket을 얘기하시는 것 같아요!! 공부 되게 열심히 하셨네요!! 
저 답변에서 질문입니다!! ㅎㅎ
containsKey()로 O(logN), size() 의 상수 비교를 통해 비교한다면 O(N) 시간이 걸린다면, containsKey가 더 좋은게 아닌가요?
```
Q)  map.containskey() 메서드 대신 size로 비교한 이유가 
A) containsKey메서드를 사용한다면 O(logN)의 시간이 걸립니다.
하지만 roundTable.size() 의 상수 비교를 통해 비교한다면 O(N) 시간이 걸립니다.
따라서 성능을 높이려고 작성했습니다만 큰 의미는 없어 보입니다 ㅎㅎ,,
```

2023-06-01 06:50 UTC, hyunsb commented on src/main/java/src/hangmanGame/HangmanGameRoundTable.java
> +    }
앗 상수 비교는 O(1) 시간이 걸립니다! 실수했네요! ㅎㅎ

```
이 내용은 roundId가 roundTable의 사이즈 안에서 생성된다는 내용이 베이스로 깔려야겠네요!!
그걸 이 메서드만 보고 다른 팀원들도 알 수 있을까요?
```
그렇네요,, 작성자의 설명이 필요한 코드는 이미 잘못된 코드일지도 모르겠단 생각이 드네요.
주석을 통해 roundId가 roundTable의 사이즈 안에서만 존재한다는 것을 알려야 할까요?

2023-06-02 08:41 UTC, chaewon12 approved these changes
고생하셨습니다 👍 티키타카 너무 재미있었어요

2023-06-11 04:32 UTC, hyunsb commented
이번 미션에서는 정적 팩토리 메서드, 캐싱, 컬렉션등을 사용하며
지금까지 학습했던 내용을 적극적으로 활용해보는 시간을 가질 수 있었습니다.

멘토님의 라이브코딩을 보며 객체지향의 실마리를 조금 잡은 거 같은 느낌이 들었습니다.
제 코드에 멘토님의 라이브 코딩 스타일을 적용해보려 했으나
클래스가 너무 무분별하게 나누어지는 느낌이 있어서 
만약 기회가 있다면 다음 미션에서 적용해보려 합니다.

채원님의 정성스러운 리뷰 너무 감사합니다.
제가 어떤 생각을 가지고 코드를 작성했는지 다시 정리하는 시간이 되었고
만약 프로그램을 배포했을 때 어떤 점이 지속해서 변경이 되는지에 대해 고민해보는 시간이 되었습니다.

좋은 기회를 주신 맨토님께 감사드립니다!
@ecsimsw

2023-06-11 07:41 UTC, ecsimsw commented on src/main/java/src/view/InputView.java
> +    private static String inputOf(String message) {
👍

2023-06-11 07:42 UTC, ecsimsw approved these changes
😊

2023-06-11 07:42 UTC, merged