[Hangman] 미션 제출합니다 (엄채원)
ecsimsw/java-hangman pull request #2
Opened 2023-05-31 07:37 UTC by chaewon12

# 클래스 설명
## 1. HangManApplication
- 프로그램의 시작점
- 메뉴 선택에 따라 '게임 실행', '결과 보기' 를 수행한다.

## 2. package src.hangman
### Hangman
- 행맨 게임에서 메달려 있는 '행맨'을 의미한다. 캐릭터의 개념
- 각 게임은 하나의 행맨을 가진다.
- 행맨은 `answer(정답 단어)`,`wordSize(단어 길이)`, `hiddenWord(가려진 단어)`, `life(목숨)`을 가진다 

### HangmanGame
- `GameLauncher`에서 게임이 시작될 때 `Hangman`을 전달해주고 게임 히스토리가 저장된다.
- 각 게임은 `Hangman` 이라는 캐릭터와 `gameId`, `roundIdSet(진행했던 라운드들의 id)`, `success(성공 여부)`를 가진다
- `GameRepository`에 저장된다
### HangmanRound
- 게임에 상관없이 라운드는 고유의 id를 갖는다. 
- 각 라운드는 `roungId`, `roundLife(해당 라운드에 남은 목숨)`, `roundBoard(숨겨진 단어 현황)`, `roundInput(사용자 입력)`을 가진다.

### GameLauncher
- Hangman 게임을 진행하는 클래스 
- GameLauncher 생성 시 `HangmanGame`이 생성된다.
- 게임Id, 라운드Id 의 SerialNum을 관리한다(모든 런처가 공유).
- 게임 진행 중 입력된 추측을 저장한다(`inputHistory`). 중복 추측 방지를 위함 

## 3. package src.repository
### GameRepository
- 게임을 저장하는 DB. 싱글톤으로 생성된다
- 게임을 <gameId,HangmanGame> map 에 저장한다.

### RoundRepository
- 라운드를 저장하는 DB. 싱글톤으로 생성된다
- 라운드를 <roundId,HangmanRound> map 에 저장한다.

## 4. package src.util
### InputHelper
- 안내문 출력, 사용자 입력을 수행하는 클래스
- `ou : `, `in : ` 과 같은 출력 포멧을 적용하여 출력하도록 돕는다.
- 사용자 입력에 대한  검사와 예외 처리를 수행한다

### WordBook
- 행맨 게임을 위한 정답 영단어를 저장한 enum 클래스
- 랜덤으로 하나를 반환하는 `getRandom` 메서드를 가진다 

### Description
- 입출력 안내 문자열이 정의된 클래스

## 5. package src.exception 
커스텀 exception과 error code 관련 클래스들

# 미션 진행
## 1단계
- [x] 게임 횟수와 목숨 횟수를 입력한다.
- [x] 미리 정의된 정답 단어 중 하나가 무작위로 선택된다.
- [x] 매 라운드마다 목숨의 횟수와 현재까지 추측에 성공한 점수 보드를 출력한다.
- [x] 사용자에게 문자를 입력하라는 메시지를 표시한다.
- [x] 사용자의 추측에서 일치하는 위치의 알파벳이 있다면 이를 표시한다.
- [x] 사용자가 모든 글자를 정확히 맞춘다면 축하 메시지를 안내한다.
- [x] 목숨의 횟수가 끝났다면 실패 메시지를 안내한다.
- [x] 다음 게임이 진행된다.

## 2단계
- [x] 정답과 예시에서 벗어나 나올 수 있는 잘못된 시나리오들을 생각해보고 본인의 방식대로 처리한다.

## 3단계
- [x] 각 라운드에서 진행한 라운드 결과를 저장한다. 라운드 결과에는 라운드id, 라운드에 남은 목숨 수, 라운드의 점수 보드, 사용자 추측이 포함된다.
- [x] 각 게임의 결과를 저장한다. 게임 결과에는 게임id, 사용자 성공/실패 여부, 남은 목숨 개수, 게임의 정답이 포함된다.
- [x] 게임이 종료되면 해당 게임의 결과 -> 그 게임의 각 라운드 결과를 차례로 출력한다.

## 4단계
- [x] 게임과 라운드 결과를 조회할 수 있다. 선택 메뉴를 출력한다. 메뉴에는 게임하기, 게임 결과 보기, 라운드 결과 보기가 있다.
- [x] 게임하기라면 위의 1,2단계가 그대로 진행된다.
- [x] 게임 결과 보기라면 게임의 id를 입력하고 게임 결과를 출력한다.
- [x] 라운드 결과 보기라면 라운드의 id를 입력하고 라운드 결과를 출력한다.

2023-05-31 08:33 UTC, ecsimsw requested changes

2023-05-31 08:33 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +            }catch(NoSuchElementException e){
gameRepository.getByGameId(input)에서 NoSuchElementException 을 처리하는 것은 isEmpty인 상황을 못 잡을까요?
isEmpty()를 한번 더 확인해야하나 궁금하네요.

2023-05-31 08:33 UTC, ecsimsw commented on src/main/java/src/hangman/Hangman.java
> +			hiddenWord.append('_');
만약 요구사항이 바뀌어서 히든 표시가 _에서 *로 바뀌면 어떻게 될까요?
또는 지금 상태에서 히든 상태의 개수를 구해야한다는 조건이 추가되면 어떤 변화가 생겨야할까요?

조금 더 힌트를 드리면, 여러 방식이 있을 수 있을 것 같은데 
사용자가 입력한 것 중 정답지에 있는 알파벳을 저장해두거나, 정답 문자열에는 있지만 아직 추측되지 않은 알파벳 목록을 저장해둘 수도 있겠네요!

2023-05-31 08:33 UTC, ecsimsw commented on src/main/java/src/repository/RoundRepository.java
> +	private SortedMap<Integer, HangmanRound> roundDB;	// gameId,HangmanRound
여기도 다시 한번 봐보실래요?

2023-05-31 08:35 UTC, chaewon12 commented on src/main/java/src/HangManApplication.java
> +                .filter(m -> m.getCode() == code)
NoSuchElementException 에 대한 처리를 안했네요!

2023-05-31 08:41 UTC, ecsimsw requested changes

2023-05-31 08:41 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +                .filter(m -> m.getCode() == code)
Integer 타입의 두 객체의 동등함 확인을 위해 ==을 사용해도 될까요?!

2023-05-31 08:46 UTC, chaewon12 commented on src/main/java/src/HangManApplication.java
> +                .filter(m -> m.getCode() == code)
아하..! int가 아닌 Integer 타입이기 때문에 equals()로 비교해야겠네요

2023-05-31 08:59 UTC, chaewon12 commented on src/main/java/src/HangManApplication.java
> +            }catch(NoSuchElementException e){
구분해놓은 이유가 
isEmpty() 라는 건 GameResult 자체가 없는 게임을 한 번도 플레이 하지 않는 경우이고
gameRepository.getByGameId(input)에서 NoSuchElementException 는 해당 id를 가진 게임이 없는 경우 입니다!

[application 시작] ->[게임 결과보기]를 하면 저장된 게임이 없어서 계속 NoSuchElementException이 나게되고 
그러면 탈출이 불가능한 상태로 재입력만 받게 돼서 구분했습니다

2023-05-31 09:18 UTC, chaewon12 commented on src/main/java/src/hangman/HangmanGame.java
> +	private SortedSet<Integer> roundIdSet;
네 맞아요! 
round 객체를 다 가지고 있는건 너무 무겁다고 생각해서 
id로 연결만 해줬습니다

2023-05-31 11:08 UTC, hyunsb commented
안녕하세요 채원님!

과제 진행하느라 고생 많으셨습니다!
채원님도 연휴동안 과제하셨나보네요 ㅎㅎ

토이프로젝트 때도 채원님 코드를 봤었는데 Enum을 되게 적극적으로 잘 사용하시는 것 같아요!
제가 다른 분의 코드를 리뷰할 실력은 안되지만
잘 읽히지 않는 코드나 이해가 잘 되지 않는 코드 위주로 리뷰를 남겨보겠습니다!

2023-05-31 12:13 UTC, hyunsb commented on src/main/java/src/util/WordBook.java
> +	}
이 코드는 단번에 이해하기가 조금 어려웠습니다

랜덤 숫자를 변수로 뽑아내고 이를 인덱스로 접근하는 방식은 어떨까요?
``` java
int randomIndex = new Random().nextInt(WordBook.values().length);
return values()[randomIndex].name().toLowerCase();
```
오,, `name()` 메서드는 처음 알았네요. 좋은 정보 얻고 갑니다👍

2023-05-31 12:14 UTC, hyunsb commented on src/main/java/src/HangManApplication.java
> +        return null;
이 부분은 저도 좀 의아했습니다!

2023-05-31 13:03 UTC, hyunsb commented on src/main/java/src/util/InputHelper.java
> +		System.out.println(OU);
해당 코드는 입력받는 모든 메서드에서 중복되네요!
메서드로 묶어낼 수 있지 않을까요?

2023-05-31 13:05 UTC, hyunsb commented on src/main/java/src/util/InputHelper.java
> +				}
이 부분은 저도 고민하고 있는 부분인데
try문 안에서 예외를 throw하고 바로 catch하는 것보단
input을 객체로 감싸서 검증하는 방식은 어떻게 생각하시나요?

2023-05-31 13:06 UTC, chaewon12 commented on src/main/java/src/util/WordBook.java
> +	}
제안해주신 코드가 훨씬 가독성이 좋네요!

메서드 호출을 이어서 하는 습관이 있는 것 같습니다...ㅠ 
전에 멘토님께서도 말씀해주셨던 부분인데...

2023-05-31 13:26 UTC, chaewon12 commented on src/main/java/src/hangman/Hangman.java
> +			hiddenWord.append('_');
히든표시 문제는 상수화를 해서 해결했습니다
`private static final Character HIDDEN_SPECIAL_CHARACTERS ='_';`

그리고 추측 성공한 알파벳을 저장하도록 수정해봤습니다!
히든 표시를 추측한 알파벳으로 변경하는 부분 에서 저장하면 될 것 같아서 관련 코드들을 수정했습니다~!
```java
public void guessUpdate(List<Integer> replaceIndexes,String alphabet) {
		guessedAlphabet.add(alphabet);
		replaceIndexes.forEach(
			index -> hiddenWord.replace(index,index+1,alphabet)
		);
	}
```

2023-06-01 00:46 UTC, ecsimsw commented on src/main/java/src/hangman/Hangman.java
> +			hiddenWord.append('_');
이건 제가 코드로 보여드릴게요.
숨겨진 캐릭터를 _으로 표현하는 방법도 좋고, 이따 보여드릴 방법은 숨겨진 위치나 아직 못 찾은 알파벳을 기억하고 표시는 View에서 하도록 하는 겁니다.

2023-06-01 00:47 UTC, ecsimsw commented on src/main/java/src/repository/RoundRepository.java
> +	private SortedMap<Integer, HangmanRound> roundDB;	// gameId,HangmanRound
참조 타입을 SortedMap으로 해야할까요? 
지난번에 채원님이 가급적 상위 인터페이스를 사용하라는 말씀을 해주셨는데 참조 타입으로 SortedMap을 사용할 이유가 있는지 궁금하네요.

2023-06-01 06:25 UTC, hyunsb commented on src/main/java/src/util/InputHelper.java
> +	private static final String INVALID_DELIMITER_PATTERN = ".*[^a-zA-Z0-9"+INPUT_DELIMITER+"].*";	// 영문자, 숫자, INPUT_DELIMITER 이외의 특수문자
오호 값 구분 기준이 바뀔 수 있으니
`INPUT_DELIMITER`를 변수로 관리하며 사용하셨군요!

채원님의 꼼꼼함이 보이네요,,

2023-06-01 06:28 UTC, hyunsb commented on src/main/java/src/util/InputHelper.java
> +	private static final BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
`InputStream`을 close하지 않아도 될까요?

2023-06-01 06:32 UTC, chaewon12 commented on src/main/java/src/hangman/Hangman.java
> +			hiddenWord.append('_');
아 그러면 hiddenWord를 만들지 않고 그때그때 `맞춘 알파벳의 위치`, `못찾은 알파벳 위치`을 조합해서 보여주는 방식인걸까요...?

2023-06-01 06:37 UTC, chaewon12 commented on src/main/java/src/repository/RoundRepository.java
> +	private SortedMap<Integer, HangmanRound> roundDB;	// gameId,HangmanRound
이왕이면 정렬된 map으로 들고있고 싶다고 생각해서 SortedMap으로 한거였는데

설마 SortedMap<> map = new TreeMap<>(); 이렇게 말고
Map<> map = new TreeMap<>(); 이렇게 해도 상관 없는 건가요!?

`정렬된 map` 검색했을때 다들 SortedMap<> map = new TreeMap<>(); 이렇게 써놨길래 아무 생각 없이 쓴것 같네요...

2023-06-01 06:39 UTC, chaewon12 commented on src/main/java/src/util/InputHelper.java
> +			}
와 묶을 수 있다는 게 생각이 안났어요!
고치면 더 깔끔하겠네요

2023-06-01 06:40 UTC, hyunsb commented on src/main/java/src/hangman/Hangman.java
> +			hiddenWord.append('_');
헉 저도 궁금하네요!

2023-06-01 06:41 UTC, chaewon12 commented on src/main/java/src/util/InputHelper.java
> +		System.out.println(OU);
오.. 그러네요
그런데 묶어내기엔 너무 자잘한? 사소한? 느낌이 들긴 하는데
그래도 빼는게 좋을까요?

2023-06-01 06:45 UTC, chaewon12 commented on src/main/java/src/repository/GameRepository.java
> +	private SortedMap<Integer,HangmanGame> gameDB;	// gameId,HangmanGame
음... '만약 지금까지의 라운드, 게임을 모두 출력하는 기능이 생긴다면?'
'그럼 저장할 때부터 정렬된 상태면 좋겠다~' 하고  TreeMap으로 한 것 같아요  

지금의 코드에서는 메리트가 없는게 맞아요..!ㅎ

2023-06-01 06:49 UTC, ecsimsw commented on src/main/java/src/repository/RoundRepository.java
> +	private SortedMap<Integer, HangmanRound> roundDB;	// gameId,HangmanRound
구현체가 SortedMap이니 데이터는 순서가 있는 Set이 되겠고, 꼭 SortedMap 만의 기능을 사용할게 아니면 상관없지요~

예를 들면 아래처럼 SortedMap만이 갖는 기능을 사용하려면 SortedMap으로 선언해야겠지만 그렇지 않은 경우에는 채원님이 학습해주신대로 인터페이스로 빼면 구현체를 쉽게 바꿀 수 있을 것 같다는 생각이 듭니다!
```
SortedMap<K,V> subMap(K fromKey, K toKey);
```

2023-06-01 06:58 UTC, chaewon12 commented on src/main/java/src/util/InputHelper.java
> +	private static final BufferedReader reader = new BufferedReader(new InputStreamReader(System.in));
앗 닫아줘야겠네요...!

2023-06-01 07:00 UTC, ecsimsw commented on src/main/java/src/repository/GameRepository.java
> +	private SortedMap<Integer,HangmanGame> gameDB;	// gameId,HangmanGame
꼼꼼한 리뷰와 답변 감사합니다 :)

2023-06-01 07:09 UTC, hyunsb commented on src/main/java/src/HangManApplication.java
> +        Supplier<Void> function;
저는 개인적으로 `fianl`이 붙어있는 게 조금 더 예쁜 코드라고 생각해요!

2023-06-01 07:10 UTC, hyunsb commented on src/main/java/src/HangManApplication.java
> +                    .toString()
스트림도 잘 사용하시네요 👍👍
저는 아직 연습이 필요합니다 ㅎㅎ

2023-06-01 07:26 UTC, chaewon12 commented on src/main/java/src/util/InputHelper.java
> +				}
검증하는 클래스를 따로 만들고 검증하는 방식인거죠?
그러면 이런식으로 작성이 되는걸까요?
```java
InputObject inputObject = new InputObject(input);

try {
    inputObject.validate();
} catch (Exception e) {

}
```

현수님 코드 리뷰하면서 본 것 같은데 좋은 방법인 것 같아요! 
고민되는 부분은 그러면 입력값마다 Lift, Alpha, ... 클래스를 만드는게 좋을까요
아니면  InputObject 클래스를 하나 만들고 안에 lifeValidate(), alphaValidate() 이런식으로 메서드를 나누는게 좋을까요...

첫번째 방식은 입력값별로 구분이 딱 되고 역할의 범위도 맞는데 그러면 클래스가 너무 많아지는거 아닌가 고민이고
두번째 방식은 하나만 있으면 되니 깔끔하긴 하지만 범위가 너무 커질 것 같아요

2023-06-01 07:27 UTC, chaewon12 commented on src/main/java/src/repository/RoundRepository.java
> +	private SortedMap<Integer, HangmanRound> roundDB;	// gameId,HangmanRound
넵! 알겠습니다

2023-06-01 07:46 UTC, chaewon12 commented on src/main/java/src/HangManApplication.java
> +        Supplier<Void> function;
혹시나 변경될 수 있을 가능성을 배제하고 싶어서 붙이는 거죠?!

2023-06-01 08:50 UTC, hyunsb commented on src/main/java/src/util/InputHelper.java
> +				}
맞아요 저도 고민입니다 ㅋㅋㅋㅠㅠ
```
Life, Alpha, ... 클래스를 만드는게
```
각자 클래스를 만들면 캡슐화가 되고 
입력 값에 의한 검증에서 객체가 가지고있는 값에 의한 검증이 이루어진다고 생각해서 좋은 방법이라고 생각했어요.

input 값을 검증하는 것이 아닌 input 값을 각자 클래스의 생성자에서 입력 값이
내가 가지고 있어야 하는 멤버에 적절한지 판단하는 거죠.
```java
try {
   String input = scanner.nextLine();
   if (input 조건1) throw new Exception();
   if (input 조건2) throw new Exception();
   return input;
} catch (Exception e) {
    // 예외 처리
}
``` 
이러한 입력 값에 대한 검증이 아닌
```java
try {
    String input = scanner.nextLine();
    return new SingleAlphabet(input);  // 해당 래퍼 클래스에 적합한 값인지는 클래스 안에서 결정됨
} catch (Exception e) {
   // 예외 처리
}
```
객체에서 값에 의한 검증이 이루어지는 형태입니다.

입력 메서드에 대한 반환값도 객체를 통해 이루어지니 가독성도 올라간다고 생각해요.
문제는 입력이 너무 빈번하게 일어난다면? 
저는 불필요한 인스턴스가 너무 많이 생기는 게 아닌가 라는 고민이 들었어요

그래서 인스턴스를 미리 만들고 저장한다음 꺼내서 사용하는 방식을 쓰자!
라고 생각해서 구현을 해봤는데
이렇게되면 객체가 값을 검증한 이후 생성되는 꼴이 아니라
사용자가 값을 꺼낼 때 객체 안에서 입력 값에 의한 검증이 이루어져 버리네용

말로 설명하기 참 어려운데 저도 고민중이랍니다 😥

2023-06-01 10:25 UTC, chaewon12 commented on src/main/java/src/util/InputHelper.java
> +				}
아니면 검증을 위해  lifeValidator, alphabetValidator, ...를 만드는 건 어떨까요?
목숨은 결국 행맨 초기화에만 쓰이고 버려지는 입력인데  객체로 쌓아서 받아야 하나 하는 생각이 들어서요
객체로 받으면 또 값을 얻으려면 한 번 더 접근이 필요하고요...

2023-06-01 10:57 UTC, hyunsb commented on src/main/java/src/util/InputHelper.java
> +				}
그쵸 저도 그렇게 계속 고민이 순환되네요

2023-06-02 08:32 UTC, hyunsb approved these changes
수고하셨습니다!

2023-06-14 04:42 UTC, chaewon12 commented
먼저, 좋은 미션을 내주신 멘토님께 감사드립니다~!
역시 코드를 짜보며 배우는게 잘 와닿고 기억에도 오래 남는 것 같습니다

요구사항이 단계별로 있어서 
구조를 어떻게 해야 다음 단계로 넘어갈 때 변경이 적을까 고민 하면서 짜기도 하고
이를 이용해서 기능별, 단계별 commit 쪼개기, 리팩토링 하는 연습도 할 수 있었습니다!ㅎㅎ

꼼꼼한 피어리뷰를 해주신 현수님도 감사했습니다! 
제가 놓친 부분도 찾아주시고 input 검증 방법에 대한 고민을 같이 해주셔서 
정말 재미있고 많이 배웠던 시간이었습니다 

미션을 마치면서 기억해두고 싶은 내용은
`객체지향에 꽂혀서 무분별한 클래스 나눈건 아닌지 의심해봐야한다` 
단지 클래스 나누기에만 집중하다보면 더 객체지향적이지 않은 코드가 나올 수 있다고 느꼈습니다 

@ecsimsw

2023-06-14 09:23 UTC, merged