[Hangman] 미션 제출합니다 (선예은)
ecsimsw/java-hangman pull request #3
Opened 2023-05-31 18:48 UTC by dpdmstjs

2023-06-02 07:45 UTC, Ussu1112 reviewed
안녕하세요 예은님!

코드를 실제로 구동해보면서 오류가 발생하는 부분이 있는지 확인해보면서 
로직이나 예외처리에 놓친 부분에 대한 리뷰를 남겨보았습니다.

확인해보시고 고민이 되는 부분이 있으시면 같이 고민해보는 것도 좋을 것 같습니다!
미션 고생하셨습니다!😊

2023-06-02 07:45 UTC, Ussu1112 commented on src/main/java/src/HangManApplication.java
> +        gameInfoList.get(index).displayGameResult();
`gameInfoList`가 입력이 되지 않았을 때는 if문 의해 return될 수 있지만
`gameInfoList`에 데이터가 있는 경우 입력 받은 gameId가 해당 리스트 범위에 없는 값을 get하려고 할 때
`IndexOutOfBoundsException` 예외가 발생하네요!

2023-06-02 07:45 UTC, Ussu1112 commented on src/main/java/src/HangManApplication.java
> +        int index = (gameId - 1);
입력 받은 값과 인덱스의 위치가 다를 때 어떻게 변경하면 좋을까요? 🤔
`index`를 정의하는 것이 제 생각엔 약간 하드코딩 하는 것 같습니다!
gameId -1 를 감싼 괄호도 의미 없는 듯 합니다!

2023-06-02 07:45 UTC, Ussu1112 commented on src/main/java/src/RoundInfo.java
> +    private String guess;
gameInfo 클래스에 있는 guess와 같은 이름을 하고 있지만
약간 다른 의미를 갖고 있는 것 같습니다.
변수 명을 변경해보시는 건 어떨까요?

2023-06-02 09:34 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +                }
엇..! 그렇네요
리뷰해 주신 대로 `number LivesnumberLives`가 보존될 수 있도록 리팩토링했습니다. 꼼꼼하게 봐주셔서 감사해요.  😊

2023-06-02 09:37 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +        int index = (gameId - 1);
음.. 저도 입력받은 값과 인덱스의 위치가 다를 때 어떻게 변경하면 좋을까 고민이 많이 되었던 부분이에요
태형님이라면 어떻게 변경하셨을 것 같나요??

2023-06-02 09:55 UTC, dpdmstjs commented on src/main/java/src/RoundInfo.java
> +    private String guess;
그러네요. gameInfo에 가지고 있는 guess는 추측을 성공했는지 실패했는지 판단하는 변수여서 변수명이 어울리지 않네요..!
`isGameSuccess` 변수명으로 변경했습니다 😊

2023-06-03 16:54 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +            int inputNumber = scanner.nextInt();
`InputMismatchException` 에 대한 예외처리로 `nextLine()` 메서드를 사용하여 버퍼를 비워주는 방식으로 처리해 봤습니다!
Scanner를 사용하여 입력을 처리할 때, 버퍼를 비우는 방법으로는 `nextLine()`과 `skip()` 등이 있다는 것을 알았습니다. 
태형님이 생각하시기에 이 요구 상황에는 어떠한 방법이 더 적절하다고 생각하시나요?

2023-06-04 13:04 UTC, Ussu1112 commented on src/main/java/src/HangManApplication.java
> +        int index = (gameId - 1);
저 같은 경우에는 클래스에 gameId에 필드로 생성하여 저장하였는데,
이때 gameId에 들어갈 값을 `private static int gameSeqNum = 1;`로 지정해두고 시퀀스 번호를 대신해서 넣었습니다!
생성자에서는 `gameSeqNum++;` 를 진행하여 들어오는 순서대로 넘버링을 해주었습니다😊

2023-06-04 13:07 UTC, Ussu1112 commented on src/main/java/src/HangManApplication.java
> +            int inputNumber = scanner.nextInt();
저도 자세한 내용은 몰라서 찾아봤습니다!
Scanner 클래스의 skip() 메서드는 특정 패턴을 갖는 텍스트를 건너뛰는 데 사용한다고 하네요!
콘솔에서 메뉴를 통해 이동해야하고 길게 입력하는 것이 아니니 저는 `nextLine()`이 더 나을 듯 합니다.

2023-06-11 16:33 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +        gameInfoList.get(index).displayGameResult();
`gameInfoList`의 사이즈 보다 크거나 0과 같다면 return 되도록 변경하였습니다!

2023-06-11 16:37 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +                String[] inputNumbers = input.split(",");
입력 형식을 맞추지 않고 입력하는 경우 `ArrayIndexOutOfBoundsException`, `NumberFormatException` 으로,
음수를 입력한 경우 `IllegalArgumentException`으로 예외 처리 하였습니다!

2023-06-14 13:59 UTC, ecsimsw requested changes

2023-06-14 13:59 UTC, ecsimsw commented on src/main/java/src/GameInfo.java
> +    GameInfo(int gameId, String answer, boolean isGameSuccess, int lives, List<RoundInfo> roundList) {
접근 제한자가 없는 것은 의도하신건가요?

2023-06-14 13:59 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +        if (gameInfoList.size() == numOfElements || gameInfoList.size() < gameId) {
'gameInfoList.size() == numOfElements' 는 gameInfoList의 사이즈가 0인지 확인하는 조건인가요?

2023-06-14 13:59 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +            if (key == roundId) {
아래처럼 containsKey를 써도 되었을까요?
``` java
if(roundInfoMap.containsKey(roundId)) {
   System.out.println(roundInfoMap.get(key+index));
}
```

만약 라운드id가 map에 키로 없는 입력이라면 예외로 처리되었으면 좋겠네요 ㅎㅎ

2023-06-15 11:46 UTC, dpdmstjs commented
이번 미션을 통해 제가 부족한 부분이었던 구현, 예외 처리, 컬렉션 연습을 할 수 있었습니다.
피어 리뷰 덕분에 남의 코드를 보고 읽어보는 연습이 많이 되었고,
다른 사람의 리뷰를 보면서 나한테도 해당이 되는 리뷰들이 있는지 확인해 보면서 리팩토링해 볼 수 있었습니다.


또한 태형님의 리뷰를 통해서 예외 처리, 요구사항 확인, 변수명 등 배운 점이 매우 많았습니다.
코드 리뷰를 어떻게 해야 하나 고민되었는데 태형님의 정성스러운 리뷰 덕분에 코드 리뷰 작성할 때 도움이 많이 되었습니다. 감사합니다!


구현 능력 연습할 수 있도록 도와주신 멘토님께 감사드립니다!!!
@ecsimsw

2023-06-15 11:48 UTC, merged