[Hangmen] 미션 제출합니다 by 송태형
ecsimsw/java-hangman pull request #4
Opened 2023-06-01 14:23 UTC by Ussu1112

안녕하세요 멘토님!
좋은 미션을 주셔서 또 한번 코드리뷰를 더 받게 되었습니다.
저번 토이프로젝트때 와는 다르게 기초 소스가 없어 클래스를 처음부터 설계해보는 좋은 기회가 되었습니다.

아직 조금 미흡한 부분이 있지만 리팩토링 계속 진행해보겠습니다!

### 1단계 

- [X] 게임 횟수와 목숨 횟수를 입력한다.    
- [X] 미리 정의된 정답 단어 중 하나가 무작위로 선택된다.
- [X] 매 라운드마다 목숨의 횟수와 현재까지 추측에 성공한 점수 보드를 출력한다.
- [X] 사용자에게 문자를 입력하라는 메시지를 표시한다.
- [X] 사용자의 추측에서 일치하는 위치의 알파벳이 있다면 이를 표시한다. 
- [X] 사용자가 모든 글자를 정확히 맞춘다면 축하 메시지를 안내한다.
- [X] 목숨의 횟수가 끝났다면 실패 메시지를 안내한다.
- [X] 다음 게임이 진행된다.

### 2단계 
정답과 예시에서 벗어나 나올 수 있는 잘못된 시나리오들을 생각해보고 본인의 방식대로 처리한다.         
예시) 사용자가 잘못된 형식의 추측을 입력할 경우 안내 메시지와 함께 재입력 프로세스를 진행한다. 
- while문 과 try-catch문을 사용하여 재입력 프로세스를 진행한다.
- 숫자 입력 시
  - 요구하는 숫자의 범위가 벗어나는 경우
  - 숫자가 아닌 문자의 형태로 입력되는 경우 
- 문자 입력시
  - 문자가 아닌 문자열을 입력하는 경우
  - 요구하는 문자의 범위를 벗어나는 경우
  - 대소문자 구분 없이 입력 후 비교 시 소문자로 일관하게 비교
- 게임 라운드 수와 라이프 입력 시(int ,int 형태)
  - 올바른 형태로 입력되지 않은 경우
  - 숫자가 아닌 문자의 형태로 입력되는 경

추가 구현)
문제를 담는 problem 클래스를 생성하고 20개씩 저장 후 게임이 생성 될 때 문제 갯수만큼 랜덤으로 뽑아온다.
- 20개 초과의 라운드 입력 시 예외처리

### 3단계 
- [X] 각 라운드에서 진행한 라운드 결과를 저장한다. 
- [X] 라운드 결과에는 라운드id, 라운드에 남은 목숨 수, 라운드의 점수 보드, 사용자 추측이 포함된다.    
- [X] 각 게임의 결과를 저장한다. 게임 결과에는 게임id, 사용자 성공/실패 여부, 남은 목숨 개수, 게임의 정답이 포함된다.
- [X] 게임이 종료되면 해당 게임의 결과 -> 그 게임의 각 라운드 결과를 차례로 출력한다.

게임과 라운드 결과 값을 저장하는 gameResult, roundResult 클래스를 선언하고 
전체 데이터에 대한 부분은 싱글톤으로 저장했습니다.
라운드 결과 출력 시 라운드ID값만 나오는 것은 의미가 없다고 생각해서 
roundResult에 gameId값을 외래키로 가지고 있으면서 조회 시 gameId와 함께 조회 되도록 변경해보았습니다.

### 4단계
- [X] 게임과 라운드 결과를 조회할 수 있다. 
- [X] 선택 메뉴를 출력한다. 
- [X] 메뉴에는 게임하기, 게임 결과 보기, 라운드 결과 보기가 있다.   
- [X] 게임 결과 보기라면 게임의 id를 입력하고 게임 결과를 출력한다.  
- [X] 라운드 결과 보기라면 라운드의 id를 입력하고 라운드 결과를 출력한다.

2023-06-04 16:28 UTC, inyoung0215 commented
안녕하세요. 태형님! 너무 고생하셨습니다. 클래스를 너무 깔끔하게 나눠주셨네요. 예외처리도 너무 깔끔하고, animal/body로 게임 결과를 정리해주신것도 깔끔하네요. 코드 보면서 많이 배워갑니다!ㅎㅎ

2023-06-11 07:56 UTC, ecsimsw requested changes

2023-06-11 07:56 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +                int life = game.getLife();
지금 상태로는 life는 음수일 수도, 불가능한 수일 수도 있을 것 같아요!!
물론 game.getLife에서 처리하셨겠지만 game.getLife를 짠 사람과 다른 사람이 이 로직을 짜야한다면 life의 유효함을 확인하려고 game.getLife를 조사해야할 것 같아요.

categoryName도 마찬가지 입니다 ㅎㅎ

2023-06-11 07:56 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +                life = -1;
life가 -1이면 반복문에서 나가는 것을 확인하기 위해선 84번째줄의 while 문 조건까지 쭉 올려서 확인해야할 것 같아요. 
그냥 break로 빠져나가는 것과 어떤 차이가 있을까요?

2023-06-11 07:56 UTC, ecsimsw commented on src/main/java/src/game/Game.java
> +            Class<?> enumClass = Class.forName("src.problem." + categoryName);
오호 카테고리라는 재밌는 기능을 추가하셨네요!!! 멋지십니다.

근데 '"src.problem." + categoryName'는 하드 코딩이네요!! 예를 들면 problem의 패키지명이나 파일 위치를 다른 개발자가 옮겨버리면 문제가 됨을 확인할 수 있는 방법이 있을까요?

조금 더 힌트를 드리면 카테고리를 마찬가지 enum으로 만들어 관리할 수 있겠네요!!
Categeory는 Animal, Body 등이 담겨있고, Categeory.getContentsByCategoryName(categoryName);

2023-06-13 05:33 UTC, Ussu1112 commented on src/main/java/src/game/Game.java
> +            Class<?> enumClass = Class.forName("src.problem." + categoryName);
기존에 문제 enum클래스를 가지고 있던 `ProblemList`을 만들어 뒀었는데 활용을 하지 않았던 거 같네요.
하드코딩 된 부분을 enum클래스에 `className`을 저장하여 클래스를 찾아갈 수 있도록 변경해보았습니다.
```java
ANIMAL("Animal",Animal.class.getName()),
BODY("Body",Body.class.getName());
```
`ProblemList`에 `getContentsByCategoryName` 메소드를 만들어 기존에 `createProblems` 메소드를 대체했습니다!

2023-06-13 06:53 UTC, inyoung0215 reviewed
제가 comment를 submit하지 않아서 저에게만 노출되었었나봐요ㅠㅠ 죄송합니다ㅠㅠㅠ

2023-06-13 10:48 UTC, Ussu1112 commented on src/main/java/src/HangManApplication.java
> +                int life = game.getLife();
다른 사람과의 협업 상황이라고 생각해보니 보기가 힘든 부분이 있는 것 같습니다.
그 생각은 못해봤던 거 같네요🤣

`getLife()` 안에서 입력 받는 부분 -> 입력 하는 값이 올바른 포맷인지 유효성 검증 
`int life = game.getLife();` 입력 이후 -> life에 저장된 값이 올바른 값인지 유효성 검증
이런 식으로 나눠서 유효성 검증을 하라는 말씀이신가요?🤔

2023-06-13 11:01 UTC, Ussu1112 commented on src/main/java/src/game/Game.java
> +            Class<?> enumClass = Class.forName("src.problem." + categoryName);
처음 의도했던 것은 문제 정보를 각자의 enum클래스로 관리하고 
그 클래스명(categoryName)을 입력 받으면 `Animal` 이나 `Body`가 가지고 있는 value값을 가지고 오고 싶었습니다!

아마도 하드코딩 된 부분이 있어서 제대로 동작하지 않았던 것 같네요!

2023-06-13 13:08 UTC, Ussu1112 commented on src/main/java/src/game/Game.java
> +            }
다시 보니까 problems에 다시 넣고 있네요🤣
enum클래스의 리스트를 가져와 gameRound 수 만큼 따로 리스트로 빼려는 목적이었습니다.
리플렉션에서 하드코딩 된 부분도 수정해서 클래스 구조를 변경해보았습니다!

commit: [e578a15](https://github.com/ecsimsw/java-hangman/pull/4/commits/e578a156103f76bca6a64f1113313c5191cb82a1#diff-3268f2ceef75f82c23e880bb1158e60122133ceb2321e6f1315e6d71a0e58b2fR84)

2023-06-14 09:26 UTC, inyoung0215 approved these changes

2023-06-14 09:46 UTC, ecsimsw requested changes

2023-06-14 09:46 UTC, ecsimsw commented on src/main/java/src/problem/ProblemList.java
> +    }
``` java
public enum ProblemList {
    ANIMAL("Animal", Animal.values()),
    BODY("Body", Body.values());

    private final String categoryName;
    private final List<String> problemNames;

    ProblemList(String category, Problem[] problemContents) {
        this.categoryName = category;
        this.problemNames = Arrays.stream(problemContents).map(Problem::getName).collect(Collectors.toList());
    }

    public String getCategoryName() {
        return categoryName;
    }
    
    public static List<String> getContentsByCategoryName(String categoryName){
        for (ProblemList category : ProblemList.values()) {
            if (category.categoryName.equals(categoryName)) {
                return category.problemNames;
            }
        }
        throw new IllegalArgumentException("없는 카테고리 이름입니다.");
    }
}
```

리플렉션을 지양하셨는데 좋은 방법이 생각이 안나신거 같아 방향드립니다!!!
방법은 많을 것 같으니 꼭 위 코드에 갇히지 않고, 그리고 리플렉션 사용에 갇히지 않고 생각해보시면 좋을 것 같아요 ㅎㅎ

2023-06-14 09:48 UTC, ecsimsw commented on src/main/java/src/problem/ProblemList.java
> +    }
그나저나 ProblemList랑 Category라는 표현이 섞여 사용되네요 😊
``` java
for (ProblemList category : ProblemList.values()) 
```
하나로 통일하시면 더 읽기 편할 것 같아요.

2023-06-15 01:51 UTC, Ussu1112 commented on src/main/java/src/problem/ProblemList.java
> +    }
리플렉션을 제거하니까 훨씬 더 깔끔한 코드가 된 것 같습니다..👍
`problem/category` 혼용되어 하나로 수정하였습니다!

2023-06-15 03:42 UTC, ecsimsw requested changes

2023-06-15 03:42 UTC, ecsimsw commented on src/main/java/src/problem/ProblemList.java
> +    public static List<String> getContentsByCategoryName(String problemType){
```suggestion
    public static List<String> getProblemsByProblemType(String problemType){
```

2023-06-15 11:32 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +                int life = game.getLife();
``` java
Life life = game.getLife();
```

으로 life 변수는 그 인스턴스 자체로 목숨에 대한 요구사항이 만족되었구나~ 확인되어도 좋을 것 같다는 피드백이었습니다.

2023-06-15 11:33 UTC, inyoung0215 approved these changes

2023-06-18 08:26 UTC, ecsimsw approved these changes

2023-06-28 07:46 UTC, Ussu1112 commented
@ecsimsw 
안녕하세요 멘토님!
이번 프로젝트를 통해서 자바 애플리케이션을 처음부터 설계해보는 좋은 기회였습니다.
프로젝트을 진행하면서 enum클래스를 활용하여 문제를 랜덤으로 가져오거나 메뉴 관리를 해서 좀 더 깔끔하게 표시할 수 있었습니다.
또한 클래스를 목적에 맞게 분리하거나 시행착오로 겪었던 리플렉션을 활용해 볼 수 있었습니다.
추가로 멘토링 시간에 주신 팁으로 메소드의 depth를 줄이거나, 메소드의 내용을 early return, ealry break로 변경하는 리팩토링 해보았습니다. 
아직은 미흡하지만 배우는 것이 많았던 프로젝트였습니다! 감사합니다!

2023-06-28 08:34 UTC, merged