황인영
ecsimsw/java-hangman pull request #5
Opened 2023-06-01 21:26 UTC by inyoung0215

단계별로 진행하면서 기존 1단계에서 만들었던 클래스 말고 다른 클래스를 추가로 생성하거나 코드를 리팩토링하는것이 어렵다고 느꼈습니다ㅠ.ㅠ
일단 최대한 깔끔하게 정리해보려고 노력했습니다!
객체 생성 이유에 대한 이해가 좀 부족한것같아요ㅠ.ㅠ
어떤 객체를 생성해야 하고 어떤 패턴(?)으로 만들어야하는지 바로바로 생각이 안떠오릅니다.
예전 자바 과제랑 뭔가 달라진게 없는거 같은..
그래도 재미있었습니다!

2023-06-03 11:17 UTC, sdfgx123 commented
인영님 안녕하세요,
이번에 처음 제대로 다른 분의 코드를 리뷰해 봅니다.

저도 피어 리뷰는 처음이라 많이 부족하지만 최대한 열심히 해보겠습니다~!

2023-06-03 11:44 UTC, sdfgx123 commented
코드를 돌려봤는데 게임이 시작될 때마다 설정된 목숨도 같이 초기화 되는 걸 확인했습니다. 저 같은 경우는 목숨을 한 번 초기화 하면 모든 게임이 끝날 때까지 목숨을 초기화 하지 않고 유지하도록 구현 했습니다.

이건 요구사항을 어떻게 해석하느냐에 따라 달라지는 문제라고 생각하는데, 인영님의 구현이 맞다고 가정하고 리뷰를 진행해 보겠습니다. 혹시 제가 요구사항을 잘못 이해한 건가요??? 맞다면 말씀 부탁드립니다!

추가적으로, 메인 함수에서 분기하실 때, Enhanced switch 블록을 사용하셨던데, 이 기능이 자바 12버전 이후부터 지원하는 기능이라 11 버전을 쓰는 저는 컴파일이 안되더라고요 😅

그래서 코드를 돌려볼 때 제 로컬 환경에서 이 부분만 임의로 수정해 봤습니다!

2023-06-04 16:49 UTC, inyoung0215 commented
아하 요구사항에서는 따로 적혀져 있진 않아서, 저는 라운드마다 목숨을 초기화해주는 걸로 해석해보았습니다!
자바 버전에 관련된 코멘트 감사합니다! 안그래도 자꾸 17 최신버전으로 자동으로 옮겨져서ㅠ.ㅠ 이번기회에 저도 11버전으로 고정으로 사용해보겠습니다ㅎㅎ

2023-06-11 08:05 UTC, ecsimsw requested changes

2023-06-11 08:05 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +    private static final Scanner scanner = new Scanner(System.in);
스캐너는 사용이 끝나면 닫아줘야합니다!

try-catch-resource를 공부하시고 사용해보셔도 좋을 것 같아요 ㅎㅎ

2023-06-11 08:05 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
위에서 gameNum와 life를 받아서 'isValidInput = true;'인지 체크하는데, invalid이면 어떻게 되나요?
그래도 반복문 없이 user.getLife 아래의 로직을 호출하는게 똑같지 않나요?

2023-06-13 06:52 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
gameNum과 life를 "숫자,숫자" 입력을 유도하기 위해 반복문을 사용했습니다. 해당 형태로 입력하지 않으면 다시 입력기회를 주기위해서..?

2023-06-13 07:35 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +    private static final Scanner scanner = new Scanner(System.in);
try catch resource로 수정해보았습니다! 이렇게 사용하는것이 맞을까요ㅎㅎ
scanner를 매개변수로 보내는 게 처음이라 조금 낯서네요.

2023-06-14 10:10 UTC, ecsimsw requested changes

2023-06-14 10:10 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +    private static final Scanner scanner = new Scanner(System.in);
오잉 적용안된거 같은데요?

``` java
try(Scanner scanner = new Scanner(System.in)){
        ...
}  
```

2023-06-14 11:03 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +    private static final Scanner scanner = new Scanner(System.in);
10c92ef1fc05a17c42e9bc3379cd0f489ac45410
엇 혹시 커밋이 안되었나요..?

2023-06-14 13:49 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +    private static final Scanner scanner = new Scanner(System.in);
되었네요!

2023-06-14 13:50 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
👍

2023-06-15 06:29 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +    }
gameId는 게임횟수, 목숨을 입력하는 게임이 늘어날때마다 증가하는 Id이고,
roundId는 gameId = 1 일때 게임횟수를 2로 입력한다면, gameId = 1, roundId = 1&2 이렇게 구성되는 거라고 생각했습니다!
정호님 말씀처럼 "roundId 1을 입력했을 때, 게임을 3번 했다면 같은 roundId가 3개 있기 때문에" gameId값을 먼저 받은 건데, 정호님께서는 roundId는 gameId와 관련없이 독자적으로 증가되도록 짜신 걸까요??

2023-06-15 06:34 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
@sdfgx123 
네네! 입력기회를 다시 주기 위해 while문 사용했습니다! 정호님은 어떻게 입력받으셨나요? 더 좋은 방법이 있는지 궁금하네요🤔

2023-06-15 06:37 UTC, inyoung0215 commented on src/main/java/src/GameAnswer.java
> +        return chars;
오 좋은 피드백 감사합니다ㅎㅎ
chars는 생각없이 정한 변수명이라 정곡을 찔렸네요.
setBlind > hideAnswer나 hideWord는 어떨까요?
chars > answer나 word로 바꾸면서요!
다른 좋은 네이밍 추천해주시면 감사하겠습니다! 👍

2023-06-15 06:44 UTC, sdfgx123 commented on src/main/java/src/HangManApplication.java
> +    }
아 무슨 말씀이신지 이해했습니다! 네 저는 gameId랑 roundId를 독립적으로 설계했습니다. 저는 roundId가 gameId에 종속되지 않게끔 하기 위해서 저 둘을 분리했는데 이렇게 보면 또 구분이 되네요 ㅎㅎ

2023-06-15 06:49 UTC, sdfgx123 commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
저도 비슷하게 구현했습니다! 다만 저는 while 루프는 안 돌리고 try catch로 입력에서 예외가 잡히면 return으로 계속 재귀호출 하도록 했습니다.

2023-06-15 06:51 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +    private static final User user = new User();
오 생각해보아야 하는 부분이었는데, 감사합니다!
현재로서는 UserList클래스를 생성해서 addUser, removeUser 등 메서드로 user의 이름과 고유번호를 map?을 이용해 관리하는 방법밖에 생각이 안나네요..! 그래도 객체를 계속 생성해줘야하서 user를 관리해주는 방향만 생기고, 나머지는 비슷한것 같은데,,
다른 더 좋은 방법이 있을까요?

2023-06-15 06:53 UTC, sdfgx123 commented on src/main/java/src/GameAnswer.java
> +        return chars;
hideAnswer가 직관적으로 다가오네요!  chars도 answer랑 word 둘 다 전보다 이해하기 훨씬 쉬워진 것 같습니다!

2023-06-15 06:53 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +                    case 3 -> showRoundResult();
와 생각지 못한 부분이었습니다ㅎㅎ
항상 먼저 걸러줘야 하는 부분을 놓치네요 😓
리팩토링할때 꼭 추가해보겠습니다ㅎㅎ

2023-06-15 06:57 UTC, sdfgx123 commented on src/main/java/src/HangManApplication.java
> +    private static final User user = new User();
제 생각이랑 비슷하시네요~ 저는 개인적으로 User 클래스를 추가적으로 만들고, HangManApplication 클래스에 UserList ArrayList를 static으로 올려놓고 거기에 User들을 담는 방향으로 생각하고 있었습니다.

그런데 이 부분은 저도 좀 헷갈려서 멘토님은 어떻게 생각하시는지 궁금하네요 ㅎㅎ

2023-06-15 06:58 UTC, sdfgx123 commented on src/main/java/src/HangManApplication.java
> +    private static final User user = new User();
아아 위에 잘못 썼습니다 😅 User 클래스는 이미 구현되어 있고, userList 변수명을 가진 ArrayList를 만든다는 거죠~

2023-06-15 07:10 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
오ㅋㅋㅋ 탄성이 나오네요. 그런 방법이.. 
그럼 입력값을 받는 메서드를 따로 생성해서 이런식으로 작성하는 걸까요?
playGame()메서드의 리팩토링 방향을 고민했었는데, 좋은 방법이네요!
`static void Input(){
  try{
  //입력 로직
  } catch(){
  Input();
  }
  }`

2023-06-15 07:19 UTC, sdfgx123 commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
네 맞습니다! 그런 식으로 재귀호출 하도록 했습니다!

2023-06-15 08:59 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +                    case 3 -> showRoundResult();
`showGameResult()`와 `showRoundResult()` 메서드에 추가해보았습니다!
```
if (games.isEmpty()){
            System.out.println("진행된 게임이 없습니다.");
            return;
        }
```

2023-06-15 09:03 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
기존 `playGame()` 메서드를 `startGame()` 과 `runGame()`으로 구분해 보았는데, 메서드 명이 항상 고민이네요 🤣
입력값을 받는 부분도 따로 구분하려고 했는데, 뭔가 클래스내의 메서드가 정리가 안되는 느낌..!
```
public static void startGame() {
        try {
            System.out.println("게임 횟수와 목숨을 입력하세요.");
            String str = reader.readLine();
       ...
            runGames(user, startGameID);
        } catch (NumberFormatException e) {
            System.out.println("숫자, 숫자 형태로 입력해주세요.");
            startGame();
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
            startGame();
        } catch (IOException e) {
            System.out.println("입력 오류가 발생했습니다.");
        }
    }

2023-06-15 09:44 UTC, inyoung0215 commented on src/main/java/src/HangManApplication.java
> +    private static final User user = new User();
`UserList`클래스 생성해서 사용자 이름을 받아서 추가하는 코드로 변경해보았습니다!
```
System.out.println("사용자 이름을 입력하세요.");
            String userName = br.readLine();
            User user = new User(userName, life, gameNum);
            userList.addUser(user);

2023-06-15 11:28 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +        int userLife = user.getLife();
요런 꼴은 어떠세요?
방향만 참고 ㅎㅎ

``` java
public static void startGame() {
    GameInitInfo gameInitInfo = inputGameCountAndLife();
    runGames(gameInitInfo, startGameID);
}

public static GameInitInfo inputGameCountAndLife() {
    try {
         System.out.println("게임 횟수와 목숨을 입력하세요.");
         String str = reader.readLine();
         return new GameInitInfo(str);
    } catch (NumberFormatException e) {
        System.out.println("숫자, 숫자 형태로 입력해주세요.");
        return inputGameCountAndLife();
    } catch (IllegalArgumentException e) {
        System.out.println(e.getMessage());
        return inputGameCountAndLife();
    } catch (IOException e) {
        System.out.println("입력 오류가 발생했습니다.");
        return inputGameCountAndLife();
    }
```

2023-06-15 16:08 UTC, sdfgx123 approved these changes
고생하셨습니다~! 제가 직접 메인으로 해본 코드 리뷰는 이번이 처음인데 도움이 되셨으면 좋겠습니다. 지금까지 진행한 리뷰는 approve 하겠습니다. 😄

2023-06-16 03:21 UTC, inyoung0215 commented
@ecsimsw 
다른 수강생분과 서로 코드를 봐주면서 리뷰를 남겨보고 리팩토링 해보는 경험은 처음인데, 너무 재미있었고 정호님과 멘토님께서 너무 좋은 리뷰 해주셔서 짧은 시간이었지만 발전한 기분이었습니다ㅎㅎ 그리고 계속 리팩토링 하다보니 행맨 프로젝트에 더 애정이 가면서 코드를 더 들여다보게 되더라구요🤣 코드리뷰의 좋은 점을 또하나 발견하네요. 이렇게 좋은 기회 만들어주신 멘토님 감사합니당ㅎㅎ 그리고 정호님도 코드 리뷰해주시느라 너무 고생많으셨고, 진짜 많이 배워갑니다!

- try-catch-resource로 닫아주는것(scanner, bufferreader)
-변수명, 메서드명은 다른 개발자들이 보았을때도 명확한 의미로
- try-catch로 재귀함수 돌리는 방법
- 미리 제외할 수 있는 상황은 제외해주기! (코테문제 풀이에도 항상 놓치지만 이번 기회로 맘에 콱 박힌 기분😤)
- 항상 확장성 생각해주기
- 자바 11버전으로 변경 완료

2023-06-16 04:51 UTC, merged