[Hangmen] 미션 제출합니다 by 김경준
ecsimsw/java-hangman pull request #6
Opened 2023-06-02 04:04 UTC by kkzoone

처음으로 클래스를 만들고 설계를 해봤는데
단계별로 코드만 짜기 급급했던 거 같습니다..
추가적으로 수정해 보도록 하겠습니다
감사합니다!

2023-06-03 15:49 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +
개행 제거하시면 좋을 것 같아요! 😊

2023-06-11 08:13 UTC, ecsimsw requested changes

2023-06-11 08:13 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +                scanner = new Scanner(System.in);
스캐너는 사용 후 닫아주세요!! 

try-catch-resource를 키워드로 공부하시고 적용해보셔도 좋겠네요 ㅎㅎ

2023-06-11 08:13 UTC, ecsimsw commented on src/main/java/src/result/GameResult.java
> +        return null;
없는 id로 result로 검색을 하게 된다면 findGameResultById를 사용하는 사용자는 그 반환 값이 null임을 예상할 수 있을까요?
아래와 같은 꼴로 NullPointerException을 만들기가 딱 좋을 것 같아요.

``` java
GameResult result = findGameResultById();
result.getId(); // NPE
```

적절한 메시지나 예외 타입을 갖는 예외를 터트리거나, Optional을 키워드로 null을 어떻게 다루면 좋을지 공부하시고 적용해봐도 좋을 것 같네요!

2023-06-11 14:56 UTC, dpdmstjs commented
안녕하세요 경준님!

피어리뷰가 처음이어서 많이 부족하지만 제가 코드리뷰 받았던 부분들을 참고하여 
코드를 돌려보면서 예외처리, 로직에 놓친 부분에 대해 리뷰를 남겨보았습니다 😊

미션 고생하셨습니다!!

2023-06-11 15:33 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +
Game Result의 라운드 id와 게임 시작될 때 라운드 id가 다르게 나오는 것 같아요!

2023-06-11 16:19 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +
좋은 리뷰 감사합니다.

2023-06-11 18:33 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +            menu();
처음 run()에서 게임 횟수를 입력한 다음, 메뉴에서 `게임하기`를 선택하면 게임 횟수만큼 돌지 않고 다시 메뉴로 돌아가는 거 같아요!

2023-06-11 18:33 UTC, dpdmstjs commented on src/main/java/src/HangManApplication.java
> +        int gameNumber = gameResults.size() + 1;
처음 run()에서 게임 횟수와 목숨 횟수를 입력하고, 메뉴에서 `게임하기`를 실행하여 게임을 진행한 후,

다시 `게임하기`를 누르면 처음에 입력하였던 게임 횟수와 목숨 횟수로 게임이 실행되는데
목숨 횟수는 초기화가 되었지만, 게임 횟수는 초기화되지 않고 계속 증가하는 것 같습니다!

2023-06-18 08:26 UTC, closed without merging