Jeongho song
ecsimsw/java-hangman pull request #7
Opened 2023-06-02 07:14 UTC by sdfgx123

안녕하세요, 이번 과제에서는 어떤 베이스 코드 또는 남의 코드 없이 혼자서 만들어 봤습니다. 혼자서 해보려니 확실히 계속 테스트 중 예외가 터지고, 버그가 생기고, 의도대로 프로그램이 흘러가지 않아 중간에 계속 코드와 설계를 수정했습니다.
<br>
예외처리에 있어서 헷갈리는 게 많았습니다. 어디서 어떤 예외 처리를 해줘야 할 지 감이 오지 않았습니다. 그리고 중복되는 코드들이 있는데 이걸 어떻게 합쳐야 할 지 아직 모르겠습니다. 예를 들면, setter 또는 결과 출력 함수를 이용할 때 코드가 많이 중복되는데 이걸 해결할 방법을 찾고 있는 중입니다.
<br>

## 요구사항

### 1단계
1. 게임 횟수와 목숨 횟수를 입력한다.    
2. 미리 정의된 정답 단어 중 하나가 무작위로 선택된다.
3. 매 라운드마다 목숨의 횟수와 현재까지 추측에 성공한 점수 보드를 출력한다.
4. 사용자에게 문자를 입력하라는 메시지를 표시한다.
5. 사용자의 추측에서 일치하는 위치의 알파벳이 있다면 이를 표시한다. 
6. 사용자가 모든 글자를 정확히 맞춘다면 축하 메시지를 안내한다.
7. 목숨의 횟수가 끝났다면 실패 메시지를 안내한다.
8. 다음 게임이 진행된다.

### 2단계

### 3단계

### 4단계

2023-06-02 08:31 UTC, ecsimsw commented
당장은 중복 코드를 잡고 어떻게 설계할지보다, 더 정확하게 요구 사항을 만족시키고 꼼꼼하게 예외처리하는 구현 능력 연습에 집중하시면 좋겠네요 ㅎㅎ
잘하셨습니다!

2023-06-02 10:05 UTC, sdfgx123 commented
> 당장은 중복 코드를 잡고 어떻게 설계할지보다, 더 정확하게 요구 사항을 만족시키고 꼼꼼하게 예외처리하는 구현 능력 연습에 집중하시면 좋겠네요 ㅎㅎ 잘하셨습니다!

감사합니다! 계속 이어서 리팩토링을 할 생각입니다.

2023-06-03 15:26 UTC, dpdmstjs commented
안녕하세요. 정호 님~!
저도 정호님처럼 목숨을 한 번 초기화하면 모든 게임이 끝날 때까지 목숨을 초기화하지 않고 유지하도록 구현했었는데요.
코드 리뷰를 받아서 게임이 시작될 때마다 목숨도 초기화되도록 해봤습니다. 정호님도 한번 이렇게도 구현해 보시는 것도 좋을 것 같아 리뷰 남깁니다!

2023-06-04 11:34 UTC, sdfgx123 commented
> 

안녕하세요 예은님~!

코드 리뷰 감사합니다. 저도 이 부분에 대해 인지하고 있습니다. 다만, 인영님의 코드 리뷰에서 언급했듯이 저는 이 부분을 요구사항의 해석에 따라 달라지는 것으로 생각하고 있습니다. 따라서, 지금 당장은 저의 메인 리뷰어인 경준님 또는 멘토님의 의견에 따라 필요시 코드를 변경하려고 합니다.

물론, 메인 코드 리뷰가 끝나면 매 게임마다 목숨을 초기화 하도록 리팩토링 하는 방법도 진행해 볼 생각입니다!

2023-06-04 11:35 UTC, sdfgx123 commented
> 안녕하세요. 정호 님~! 저도 정호님처럼 목숨을 한 번 초기화하면 모든 게임이 끝날 때까지 목숨을 초기화하지 않고 유지하도록 구현했었는데요. 코드 리뷰를 받아서 게임이 시작될 때마다 목숨도 초기화되도록 해봤습니다. 정호님도 한번 이렇게도 구현해 보시는 것도 좋을 것 같아 리뷰 남깁니다!

안녕하세요 예은님~!

코드 리뷰 감사합니다. 저도 이 부분에 대해 인지하고 있습니다. 다만, 인영님의 코드 리뷰에서 언급했듯이 저는 이 부분을 요구사항의 해석에 따라 달라지는 것으로 생각하고 있습니다. 따라서, 지금 당장은 저의 메인 리뷰어인 경준님 또는 멘토님의 의견에 따라 필요시 코드를 변경하려고 합니다.

물론, 메인 코드 리뷰가 끝나면 매 게임마다 목숨을 초기화 하도록 리팩토링 하는 방법도 진행해 볼 생각입니다!

2023-06-14 10:07 UTC, ecsimsw requested changes

2023-06-14 10:07 UTC, ecsimsw commented on src/main/java/src/Game.java
> +        int idx = new Random().nextInt(wordList.size());
Random 객체를 getWordFromDict를 호출할 때마다 생성해야 할 것 같아요.
재사용할 수 있도록 하려면 어떻게 하면 좋을까요?

2023-06-14 10:07 UTC, ecsimsw commented on src/main/java/src/Game.java
> +        }
wordList가 empty라면 다시 사전에 만들어 둔 리스트로 초기화 하는 군요!! 
재밌는 기능을 추가하셨네요 ㅎㅎ

2023-06-14 10:07 UTC, ecsimsw commented on src/main/java/src/Game.java
> +                        roundResult.setStrFromUser(input);
roundResult를 미리 생성해두고 setter를 사용하는 것보다 여기에서 생성해줘도 좋겠네요.
roundResult의 프로퍼티가 100개라면 지금의 방식은 100개의 setter 호출이 필요하면서도 라인이 길어져 어떤 속성을 넣어줬지 하고 헷갈리기 쉬울거에요 ㅎㅎ

``` java
roundResults.add(new RoundResult(numOfLife, gameArray, input, roundId));
```

2023-06-15 07:05 UTC, sdfgx123 commented on src/main/java/src/Game.java
> +        }
넵 약간 NPE 체크하는 느낌이라고 생각하시면 될 것 같아요 😁

2023-06-15 07:09 UTC, sdfgx123 commented on src/main/java/src/Game.java
> +                        roundResult.setStrFromUser(input);
오 이 방법을 생각하지 못했습니다. 저도 이 부분 코드가 쓸데없이 길어지는 것 같아서 해결할 방법을 생각하고 있었는데 참신한 아이디어 얻어갑니다! 😃

2023-06-15 07:24 UTC, sdfgx123 commented on src/main/java/src/Game.java
> +                        roundResult.setStrFromUser(input);
'''java
roundResults.add(new RoundResult(RoundResult.ROUND_ID, numOfLife, new String(gameArray), input));
gameResult.addRound(roundResult);
gameResults.add(gameResult);
'''

2023-06-15 08:24 UTC, sdfgx123 commented on src/main/java/src/GameDictionary.java
> +    SENTENSE("SENTENSE", 8);
넵 필드랑 생성자 수정해서 name과 length가 통일되도록 했습니다!

commit: 752c1f2

2023-06-15 10:57 UTC, sdfgx123 commented on src/main/java/src/Game.java
> +                idx = i;
넵 파라미터로 값이 없는 등의 유효하지 않은 값이 넘어올 때를 가정해서 예외처리를 추가해 봤습니다! `idx = -1`로 처음 초기화 되는데, 이 값이 변경되지 않으면 유효하지 않은 값으로 판단하고 예외를 발생시키고 던졌습니다.

추가적으로, findGameById() 메서드 역시 비슷한 맥락이라 판단해서 같은 예외 처리를 추가했습니다. 또한, `for`문이 도는 동안 일치하는 `idx`를 찾으면 자동으로 반복이 끝나도록 `break` 라인도 추가했습니다.

2023-06-15 11:04 UTC, sdfgx123 commented on src/main/java/src/GameDictionary.java
> +    SENTENSE("SENTENSE", 8);
```java
test
```

2023-06-15 11:24 UTC, ecsimsw commented on src/main/java/src/Game.java
> +                        roundResult.setStrFromUser(input);
두번 인스턴스해도 되고, 좀 별로면 그때는 아래처럼 변수를 빼도 좋겠네요!
``` java
RoundResult roundResult = new RoundResult(numOfLife, gameArray, input); 
// 1.  ID는 숨길 수 있을 것 같아요!
// 2. gameArray를 넘기고 RoundResult에서 String으로 변환해도 되겠네요!
// 3. gameArray와 input이 뭘 의미하는지 모호한 변수명 같아요. 
roundResults.add(roundResult);
gameResult.addRound(roundResult);
```

2023-06-15 11:42 UTC, ecsimsw requested changes

2023-06-15 11:42 UTC, ecsimsw commented on src/main/java/src/HangManApplication.java
> +    public static HangManApplication getInstance() {
``` java
private static HangManApplication hangManApplication;

public static HangManApplication getInstance() {
   if (hangManApplication == null) {
       hangManApplication = new HangManApplication();
   }
}
```
매번 이런 패턴으로 싱글톤을 만드시네요! 
훌륭하지만 너무 한 패턴에 갇히지 않으셨으면 좋겠습니다. 
이제는 싱글톤에 이 똑같이 null 확인해서 생성 후 반환하는 코드가 너무 자연스러워질걸요? ㅎㅎ

예를 들면 hangManApplication을 싱글톤으로 사용하고 싶다면 아래처럼 하면 어떨까요?
hangManApplication이 딱 한번 생성되어 해당 인스턴스만 사용됨이 확실히 눈에 보이고 null인지 아닌지 확인해야하는 것조차 신경쓸 일 없어지는데.

``` java
private static final HangManApplication hangManApplication = new HangManApplication();

public static HangManApplication getInstance() {
    return hangManApplication;
}
```

2023-06-15 17:17 UTC, sdfgx123 commented on src/main/java/src/Game.java
> +                        roundResult.setStrFromUser(input);
두번째 방법으로 리팩토링 했습니다. 크게 네 가지를 수정했습니다.

1. setter를 사용하지 않고 생성자를 호출하여 roundResult를 초기화
2. RoundResult 클래스 생성자 수정 : RoundResult 생성자 호출 시 ROUND_ID를 roundId로 초기화 하도록 수정
3. gameArray, input -> 각각 discoveredChars, guessedWord로 네이밍 변경
4. gameResults에 add 하는 시점 변경 -> 기존의 매 라운드 종료시 마다 참조하는 것에서 한 게임이 끝나면 add 하도록 변경

2023-06-15 17:32 UTC, sdfgx123 commented on src/main/java/src/HangManApplication.java
> +    public static HangManApplication getInstance() {
오 그러네요! 확실히 final로 선언해 버리면 null 체크를 할 필요가 없어지네요! 조언 감사합니다! 앞으로 이런 식으로 싱글톤 활용할 것 같습니다!

Game 클래스도 싱글톤으로 선언해 놔서 똑같이 바꿔봤습니다. 😃

commit: 3544a98

2023-06-18 08:25 UTC, ecsimsw approved these changes

2023-07-05 15:58 UTC, merged