Hnagman 미션 수행 (복습, 리팩터링)
ecsimsw/java-hangman pull request #9
Opened 2023-12-06 08:07 UTC by hyunsb

기존 코드 대비
- 응집도를 높이는 방식 적용해보기
- 도메인과 뷰의 의존성을 배제하도록 변경해보기
- 테스트에 용이하도록 변경해보기

2023-12-06 11:14 UTC, ecsimsw requested changes

2023-12-06 11:14 UTC, ecsimsw commented on src/main/java/dto/newGameDto.java
> +public class newGameDto {
소문자 :)

2023-12-06 11:28 UTC, hyunsb commented on src/main/java/dto/newGameDto.java
> +public class newGameDto {
요즘 뭔가 빠르게 코드를 작성해서 그런지 대소문자 실수를 많이 허네요 😢

2023-12-06 18:11 UTC, ecsimsw approved these changes
🙇‍♂️

2023-12-06 18:11 UTC, ecsimsw commented on src/main/java/domain/hangman/Round.java
> +            throw new IllegalArgumentException("버그쓰면 안 됩니다.");
ㅋㅋㅋㅋ 예외 메시지 웃기네요.

근데 Round 랑 게임 횟수는 다른 개념을 의도하긴 했습니다. ㅎㅎ
게임 횟수 2, 목숨 4를 입력했을 때 
```
1번째 게임이 시작됩니다.
// 라운드 진행 ~ 횟수 제한 없음
2번째 게임이 시작됩니다.
// 라운드 진행 ~ 횟수 제한 없음
종료됨
```

2023-12-07 01:15 UTC, hyunsb commented on src/main/java/domain/hangman/Word.java
> +    }
헉! 버쁘실텐데 코드리뷰 너무 감사합니다 😄

예전부터 한 번 짚고 넘어가려고 했던 사항이군요!
이번 기회에 정리를 해봐야겠습니다.

``` java
class WordDto {

    // ...
    
    public static WordDto from(Word target) {
        String word = target.getWord();
        boolean[] matchIndex = target.getMatchIndex();
        return new WordDto(word, matchIndex);
    }
}
```
제가 잘 이해했다면, 이런식으로 dto쪽에서 도메인을 의존하는 꼴을 말씀하시는 게 맞나요?

멘토님이 예전에 해주셨던 model이 dto를 모르게하라라는 말씀이 떠올랐네요.
이번에 우테코 미션을 진행하면서 model <-> dto 변환 시점을 어디에 두어야 하는가에 대한 의문이 있었어요.

트레이드오프 관계라고 생각했던게
변환 시점을 model(domain)에 두게된다면 멘토님이 하셨던 말씀처럼 뷰에서 요구하는 데이터가 변경되었을 때, 코드의 변경이 domain에서 벌어지는 일이 발생할 것이라고 생각해요. (헉, 이게 결국 도메인과 뷰의 의존성을 만들어버리는 꼴이었네요)

반대로 변환 시점을 dto에 두게 된다면 domain의 상태 값을 받아오기 위해 getter를 사용해야 해요.
이러한 코드가 무분별하게 생성된다면 이는 즉, 캡슐화를 저해할 수 있다고 생각했어요.

이렇게 타이핑하면서 생각을 정리해보니 비교적 변경 가능성이 높은 객체(dto)가 변경 가능성이 낮은 객체(domain)를 의존하는 꼴이 변경에 유연할 것 같네요!

소중한 리뷰 감사합니다.

2023-12-07 01:26 UTC, hyunsb commented on src/main/java/dto/WordDto.java
> +                one = word.split("")[i];
헉! 훨씬 효율적이겠네요.

이부분은 빨리 작성하고 넘어가려고 했는데
변수명이 애매해서 스트레스를 받았던 기억이 나네요 ㅋㅋㅋ

리팩터링하면서 변수명도 함께 바꿔봐야겠습니다!

2023-12-07 05:47 UTC, ecsimsw commented on src/main/java/domain/hangman/Word.java
> +    }
오와 자답으로 좋은 답을 찾으셨네요!

변환 시점을 dto에 두게되면 domain에 두는걸 getter 때문에 고민하셨군요!!! 

저는 뷰와 컨트롤러 사이에 dto를 두는 가장 큰 이유가 '뷰의 변경에 도메인 코드를 방어하려고' 거든요.

그래서 제 dto 사용 근거에서 getter 사용을 지양하기 위해서 dto가 바뀔때마다 도메인이 바뀌는건 배보다 배꼽이 큰게 아닌가 싶네요 ㅎㅎ

근데 이건 제 근거니 현수님 근거로 이 코멘트는 잘 마무리 하시면 좋을거 같아요.

Getter 지양.. 저는 게터를 지양한다는 얘기가 필요한 상황에서 값을 꺼내기를 지양해라는 아닌거 같아요. 도메인 내부에서 처리할 일을 굳이 게터로 꺼내서 로직을 외부에서 만드는 꼴을 지양하라는 말이 getter 지양이지 않나.

외부에서 객체의 프로퍼티 값 자체가 필요한 상황에서 값을 꺼내는걸 캡슐화 저해로 생각하고 너무 보수적으로 생각하지 않아도 되지 않나 생각하고 있습니다 😀

2023-12-08 05:08 UTC, hyunsb commented on src/main/java/domain/hangman/Word.java
> +    }
멘토님 말씀 듣고 보니 Getter의 사용을 너무 보수적으로 생각하고 있었던 것 같아요.
컬렉션을 반환하는 경우만 좀 조심해서 연습해봐야겠습니다! 😄

2023-12-08 05:12 UTC, hyunsb commented on src/main/java/domain/hangman/Round.java
> +            throw new IllegalArgumentException("버그쓰면 안 됩니다.");
`n번째 게임`에서 `n`에 대한 명칭을 round라고 해버려서 ㅋㅋㅋㅋ
뭔가 헷갈리는 변수명이 되어버린 것 같아요.

횟수는 `HangmanGame` 클래스의 상태인 `count`로 선언하긴 했는데,
`HangmanGame`이 가지는 상태가 너무 많은 것 같아서 클래스를 분리해야 하나 고민이네요..

2023-12-10 15:17 UTC, closed without merging

2023-12-11 06:14 UTC, hyunsb commented
우테코 파이널 불합!